# Generated by Django 3.0.6 on 2020-06-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Department', models.CharField(max_length=70)),
                ('linkedin', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
            ],
        ),
    ]
